{"name": "test_lock_locked", "status": "failed", "statusDetails": {"message": "AssertionError: assert 404 == 304\n  -404\n  +304", "trace": "self = <test_api.Test_Api object at 0x000001C1EB8A3B50>\ndata_to_create = {'email': 'xxxR@fffff.ku', 'password': 'aaaaaaa#zzzz', 'user': 'Test_name4227'}\n\n    @allure.story('other')\n    @pytest.mark.other\n    def test_lock_locked(self, data_to_create):\n        \"\"\"Проверка разблокировки незаблокированного пользователя\"\"\"\n        self.client.add(data_to_create)\n        request = self.client.unlock(data_to_create['user'])\n>       assert request.status_code == 304\nE       assert 404 == 304\nE         -404\nE         +304\n\ntests\\test_api.py:222: AssertionError"}, "description": "Проверка разблокировки незаблокированного пользователя", "start": 1590592370233, "stop": 1590592370294, "uuid": "f58d99df-2907-4d76-aae5-21ed99a651e1", "historyId": "ac0a0f3e8b61cc189511b4c670a80b0b", "testCaseId": "c2b8e5ce64279f90963e8cf24e2198ee", "fullName": "tests.test_api.Test_Api#test_lock_locked", "labels": [{"name": "story", "value": "other"}, {"name": "tag", "value": "other"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "Test_Api"}, {"name": "host", "value": "DESKTOP-4CMVFT5"}, {"name": "thread", "value": "14640-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}]}