{"name": "test_exist_email_add", "status": "failed", "statusDetails": {"message": "AssertionError: assert 210 == 304\n  -210\n  +304", "trace": "self = <test_api.Test_Api object at 0x000002288127F850>\nauth_data = {'email': 'hello@m.net', 'password': 'hello', 'user': 'Helloworld'}\ndata_to_create = {'email': 'sssssd@fffff.ku', 'password': 'a#zzz', 'user': 'Test_name5386'}\nsql_client = <sql_client.client.MysqlOrmConnection object at 0x000002288135DB20>\n\n    @allure.story('other')\n    @pytest.mark.other\n    def test_exist_email_add(self, auth_data, data_to_create, sql_client):\n        \"\"\"Проверка, что через API пользователь с существующим email\n        не создастся\"\"\"\n        status_code = self.client.add({\n            'user': data_to_create['user'],\n            'password': data_to_create['password'],\n            'email': auth_data['email']\n        }).status_code\n        assert sql_client.select('username', data_to_create['user']) == []\n>       assert status_code == 304\nE       assert 210 == 304\nE         -210\nE         +304\n\ntests\\test_api.py:52: AssertionError"}, "description": "Проверка, что через API пользователь с существующим email\n        не создастся", "start": 1590592369614, "stop": 1590592369640, "uuid": "46f1ec51-d96a-498c-92aa-c8c80aa5c328", "historyId": "ce4f29fa23ebfc025576fab8f0e903c9", "testCaseId": "fcc8cb12056953b2953fbf2e21d315f5", "fullName": "tests.test_api.Test_Api#test_exist_email_add", "labels": [{"name": "story", "value": "other"}, {"name": "tag", "value": "other"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "Test_Api"}, {"name": "host", "value": "DESKTOP-4CMVFT5"}, {"name": "thread", "value": "19640-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}]}