{"name": "test_create_invalid_mail", "status": "passed", "description": "Проверка, что при создании при невозможном майле приложение\n        реагирует корректно", "start": 1590592405791, "stop": 1590592409091, "uuid": "f050736d-0b3e-4f13-ad10-8e14f1d4b970", "historyId": "de820890454f786cd184d11418b3cca8", "testCaseId": "f1895ff8678f7f90c1404d7be65718bf", "fullName": "tests.test_ui.Test_UI_Create#test_create_invalid_mail", "labels": [{"name": "story", "value": "other"}, {"name": "tag", "value": "other"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_ui"}, {"name": "subSuite", "value": "Test_UI_Create"}, {"name": "host", "value": "DESKTOP-4CMVFT5"}, {"name": "thread", "value": "9312-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_ui"}]}